GET http://localhost:3000/storages
Accept: application/json

###
POST http://localhost:3000/storages
Content-Type: application/json

{
    
    "name": "online",
    "location": "virtual",
    "description": "testing"
    
}

###
GET http://localhost:3000/storages/614d3b4ed344ffa8bc901bdd
Accept: application/json

###
PUT http://localhost:3000/storages/614d3b4ed344ffa8bc901bdd
Content-Type: application/json

{
    "_id": "noupdate",
    "name": "updated 3",
    "createdAt": "noUpdate"
}